window.hancock_cms.goto.constructGotoLink = (a)->
  a = $(a)
  href = a.attr('href')
  a.attr('data-href', href)
    .attr('data-gotohref', "/goto?url=#{escape(href)}")
    # .attr('onclick', "var link = this.cloneNode(true); link.href = link.getAttribute('data-gotohref'); link.onclick = null; link.click(); return false;")
    .attr('onclick', "var link = this.cloneNode(true); link.href = link.getAttribute('data-gotohref'); link.removeAttribute('onclick'); window.hancock_cms.goto.fireClick(link); return false;")
    .attr('target', '_blank')
    .attr('data-gotolink', 'true')
    .attr('rel', 'nofollow noindex noopener')
